version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
      - DB_MODE=json
      - ACCESS_TOKEN_SECRET=merch_secret_jwt_key_983749823749823
      - REFRESH_TOKEN_SECRET=merch_refresh_secret_jwt_key_88472910384729
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
